In [4]:
# This code loads the diabetes CSV file from its exact location

import pandas as pd

df = pd.read_csv(r"D:\document\AFTER_GRADUATION\DATAANALYSE\MINE\PROJECT4HEALTHCARE\diabetes_binary_health_indicators_BRFSS2015.csv")

df.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0,1,1,1,40,1,0,0,0,0,...,1,0,5,18,15,1,0,9,4,3
1,0,0,0,0,25,1,0,0,1,0,...,0,1,3,0,0,0,0,7,6,1
2,0,1,1,1,28,0,0,0,0,1,...,1,1,5,30,30,1,0,9,4,8
3,0,1,0,1,27,0,0,0,1,1,...,1,0,2,0,0,0,0,11,3,6
4,0,1,1,1,24,0,0,0,1,1,...,1,0,2,3,0,0,0,11,5,4

In [5]:
df.shape

(253680, 22)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Diabetes_binary       253680 non-null  int64
 1   HighBP                253680 non-null  int64
 2   HighChol              253680 non-null  int64
 3   CholCheck             253680 non-null  int64
 4   BMI                   253680 non-null  int64
 5   Smoker                253680 non-null  int64
 6   Stroke                253680 non-null  int64
 7   HeartDiseaseorAttack  253680 non-null  int64
 8   PhysActivity          253680 non-null  int64
 9   Fruits                253680 non-null  int64
 10  Veggies               253680 non-null  int64
 11  HvyAlcoholConsump     253680 non-null  int64
 12  AnyHealthcare         253680 non-null  int64
 13  NoDocbcCost           253680 non-null  int64
 14  GenHlth               253680 non-null  int64
 15  MentHlth              253680 non-null  int64
 16  PhysHlth              253680 non-null  int64
 17  DiffWalk              253680 non-null  int64
 18  Sex                   253680 non-null  int64
 19  Age                   253680 non-null  int64
 20  Education             253680 non-null  int64
 21  Income                253680 non-null  int64
dtypes: int64(22)
memory usage: 42.6 MB

In [7]:
# This code checks the dataset size, missing values, and duplicated rows

print("Dataset shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicated rows:")
print(df.duplicated().sum())

Dataset shape: (253680, 22)

Missing values:
Diabetes_binary         0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

Duplicated rows:
24206

In [9]:
# This code loads the original BRFSS 2015 SAS Transport file into Python

import pandas as pd

file_path = r"D:\document\AFTE'R_GRADUATION\DATAANALYSE\MINE\PROJECT4HEALTHCARE\LLCP2015.XPT"

df_raw = pd.read_sas(file_path, format="xport")

df_raw.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENUM,...,_PAREC1,_PASTAE1,_LMTACT1,_LMTWRK1,_LMTSCL1,_RFSEAT2,_RFSEAT3,_FLSHOT6,_PNEUMO2,_AIDTST3
0,1.0,1.0,b'01292015',b'01',b'29',b'2015',1200.0,2.015000e+09,2.015000e+09,1.0,...,4.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0
1,1.0,1.0,b'01202015',b'01',b'20',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,...,2.0,2.0,3.0,3.0,4.0,2.0,2.0,NaN,NaN,2.0
2,1.0,1.0,b'02012015',b'02',b'01',b'2015',1200.0,2.015000e+09,2.015000e+09,1.0,...,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,NaN
3,1.0,1.0,b'01142015',b'01',b'14',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,...,4.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,9.0
4,1.0,1.0,b'01142015',b'01',b'14',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,...,4.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0

In [10]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 441456 entries, 0 to 441455
Columns: 330 entries, _STATE to _AIDTST3
dtypes: float64(323), object(7)
memory usage: 1.1+ GB

In [11]:
# This code displays all column names from the raw BRFSS dataset

pd.set_option("display.max_rows", 400)

columns_df = pd.DataFrame(df_raw.columns, columns=["Column_Name"])
columns_df

    Column_Name
0        _STATE
1        FMONTH
2         IDATE
3        IMONTH
4          IDAY
5         IYEAR
6      DISPCODE
7         SEQNO
8          _PSU
9      CTELENUM
10     PVTRESD1
11     COLGHOUS
12     STATERES
13     CELLFON3
14       LADULT
15     NUMADULT
16       NUMMEN
17     NUMWOMEN
18     CTELNUM1
19     CELLFON2
20       CADULT
21     PVTRESD2
22     CCLGHOUS
23       CSTATE
24     LANDLINE
25      HHADULT
26      GENHLTH
27     PHYSHLTH
28     MENTHLTH
29     POORHLTH
30     HLTHPLN1
31     PERSDOC2
32      MEDCOST
33     CHECKUP1
34      BPHIGH4
35       BPMEDS
36     BLOODCHO
37      CHOLCHK
38      TOLDHI2
39     CVDINFR4
40     CVDCRHD4
41     CVDSTRK3
42      ASTHMA3
43      ASTHNOW
44     CHCSCNCR
45     CHCOCNCR
46     CHCCOPD1
47     HAVARTH3
48     ADDEPEV2
49     CHCKIDNY
50     DIABETE3
51     DIABAGE2
52          SEX
53      MARITAL
54        EDUCA
55     RENTHOM1
56     NUMHHOL2
57     NUMPHON2
58      CPDEMO1
59     VETERAN3
60      EMPLOY1
61     CHILDREN
62      INCOME2
63     INTERNET
64      WEIGHT2
65      HEIGHT3
66     PREGNANT
67     QLACTLM2
68     USEEQUIP
69        BLIND
70       DECIDE
71     DIFFWALK
72     DIFFDRES
73     DIFFALON
74     SMOKE100
75     SMOKDAY2
76     STOPSMK2
77     LASTSMK2
78      USENOW3
79      ALCDAY5
80     AVEDRNK2
81     DRNK3GE5
82     MAXDRNKS
83     FRUITJU1
84       FRUIT1
85      FVBEANS
86      FVGREEN
87      FVORANG
88     VEGETAB1
89     EXERANY2
90     EXRACT11
91     EXEROFT1
92     EXERHMM1
93     EXRACT21
94     EXEROFT2
95     EXERHMM2
96     STRENGTH
97     LMTJOIN3
98     ARTHDIS2
99     ARTHSOCL
100    JOINPAIN
101    SEATBELT
102    FLUSHOT6
103    FLSHTMY2
104    IMFVPLAC
105    PNEUVAC3
106     HIVTST6
107    HIVTSTD3
108    WHRTST10
109    PDIABTST
110    PREDIAB1
111     INSULIN
112    BLDSUGAR
113    FEETCHK2
114    DOCTDIAB
115    CHKHEMO3
116     FEETCHK
117     EYEEXAM
118     DIABEYE
119     DIABEDU
120    PAINACT2
121    QLMENTL2
122    QLSTRES2
123     QLHLTH2
124    CAREGIV1
125    CRGVREL1
126    CRGVLNG1
127    CRGVHRS1
128    CRGVPRB1
129    CRGVPERS
130    CRGVHOUS
131    CRGVMST2
132    CRGVEXPT
133    VIDFCLT2
134    VIREDIF3
135    VIPRFVS2
136    VINOCRE2
137    VIEYEXM2
138    VIINSUR2
139    VICTRCT4
140    VIGLUMA2
141    VIMACDG2
142    CIMEMLOS
143     CDHOUSE
144    CDASSIST
145      CDHELP
146    CDSOCIAL
147    CDDISCUS
148    WTCHSALT
149    LONGWTCH
150    DRADVISE
151    ASTHMAGE
152    ASATTACK
153    ASERVIST
154    ASDRVIST
155    ASRCHKUP
156    ASACTLIM
157    ASYMPTOM
158    ASNOSLEP
159    ASTHMED3
160    ASINHALR
161    HAREHAB1
162    STREHAB1
163    CVDASPRN
164    ASPUNSAF
165    RLIVPAIN
166    RDUCHART
167    RDUCSTRK
168    ARTTODAY
169     ARTHWGT
170    ARTHEXER
171     ARTHEDU
172     TETANUS
173    HPVADVC2
174    HPVADSHT
175    SHINGLE2
176      HADMAM
177     HOWLONG
178     HADPAP2
179    LASTPAP2
180     HPVTEST
181    HPLSTTST
182    HADHYST2
183    PROFEXAM
184    LENGEXAM
185    BLDSTOOL
186    LSTBLDS3
187    HADSIGM3
188    HADSGCO1
189    LASTSIG3
190    PCPSAAD2
191    PCPSADI1
192    PCPSARE1
193    PSATEST1
194     PSATIME
195    PCPSARS1
196    PCPSADE1
197    PCDMDECN
198    SCNTMNY1
199    SCNTMEL1
200    SCNTPAID
201    SCNTWRK1
202    SCNTLPAD
203    SCNTLWK1
204    SXORIENT
205    TRNSGNDR
206    RCSGENDR
207    RCSRLTN2
208    CASTHDX2
209    CASTHNO2
210    EMTSUPRT
211    LSATISFY
212    ADPLEASR
213      ADDOWN
214     ADSLEEP
215    ADENERGY
216      ADEAT1
217      ADFAIL
218     ADTHINK
219      ADMOVE
220     MISTMNT
221     ADANXEV
222      QSTVER
223     QSTLANG
224    EXACTOT1
225    EXACTOT2
226      MSCODE
227      _STSTR
228      _STRWT
229    _RAWRAKE
230    _WT2RAKE
231    _CHISPNC
232     _CRACE1
233     _CPRACE
234    _CLLCPWT
235    _DUALUSE
236    _DUALCOR
237     _LLCPWT
238     _RFHLTH
239    _HCVU651
240    _RFHYPE5
241    _CHOLCHK
242     _RFCHOL
243      _MICHD
244    _LTASTH1
245    _CASTHM1
246    _ASTHMS1
247    _DRDXAR1
248     _PRACE1
249     _MRACE1
250    _HISPANC
251       _RACE
252    _RACEG21
253    _RACEGR3
254    _RACE_G1
255    _AGEG5YR
256    _AGE65YR
257      _AGE80
258      _AGE_G
259       HTIN4
260        HTM4
261       WTKG3
262       _BMI5
263    _BMI5CAT
264     _RFBMI5
265    _CHLDCNT
266     _EDUCAG
267     _INCOMG
268    _SMOKER3
269    _RFSMOK3
270    DRNKANY5
271    DROCDY3_
272    _RFBING5
273    _DRNKWEK
274    _RFDRHV5
275    FTJUDA1_
276    FRUTDA1_
277    BEANDAY_
278    GRENDAY_
279    ORNGDAY_
280    VEGEDA1_
281    _MISFRTN
282    _MISVEGN
283    _FRTRESP
284    _VEGRESP
285    _FRUTSUM
286    _VEGESUM
287     _FRTLT1
288     _VEGLT1
289      _FRT16
290      _VEG23
291    _FRUITEX
292    _VEGETEX
293    _TOTINDA
294    METVL11_
295    METVL21_
296     MAXVO2_
297       FC60_
298    ACTIN11_
299    ACTIN21_
300     PADUR1_
301     PADUR2_
302    PAFREQ1_
303    PAFREQ2_
304    _MINAC11
305    _MINAC21
306    STRFREQ_
307    PAMISS1_
308    PAMIN11_
309    PAMIN21_
310     PA1MIN_
311    PAVIG11_
312    PAVIG21_
313    PA1VIGM_
314     _PACAT1
315    _PAINDX1
316    _PA150R2
317    _PA300R2
318    _PA30021
319    _PASTRNG
320     _PAREC1
321    _PASTAE1
322    _LMTACT1
323    _LMTWRK1
324    _LMTSCL1
325    _RFSEAT2
326    _RFSEAT3
327    _FLSHOT6
328    _PNEUMO2
329    _AIDTST3

In [12]:
# This code searches for important healthcare-related columns in the raw BRFSS dataset

keywords = [
    "DIAB", "BLOOD", "CHOL", "BMI", "SMOK", "STROKE",
    "CVD", "HEART", "EXER", "FRUIT", "VEG", "ALC",
    "GENHLTH", "MENTHLTH", "PHYSHLTH", "DIFF", "SEX",
    "AGE", "EDU", "INCOME"
]

matched_columns = [col for col in df_raw.columns if any(key in col.upper() for key in keywords)]

matched_columns_df = pd.DataFrame(matched_columns, columns=["Matched_Column"])
matched_columns_df

   Matched_Column
0         GENHLTH
1        PHYSHLTH
2        MENTHLTH
3        BLOODCHO
4         CHOLCHK
5        CVDINFR4
6        CVDCRHD4
7        CVDSTRK3
8        DIABETE3
9        DIABAGE2
10            SEX
11          EDUCA
12        INCOME2
13       DIFFWALK
14       DIFFDRES
15       DIFFALON
16       SMOKE100
17       SMOKDAY2
18        ALCDAY5
19       FRUITJU1
20         FRUIT1
21       VEGETAB1
22       EXERANY2
23       EXEROFT1
24       EXERHMM1
25       EXEROFT2
26       EXERHMM2
27       PDIABTST
28       PREDIAB1
29       DOCTDIAB
30        DIABEYE
31        DIABEDU
32       ASTHMAGE
33       CVDASPRN
34       ARTHEXER
35        ARTHEDU
36       _DUALCOR
37       _CHOLCHK
38        _RFCHOL
39       _AGEG5YR
40       _AGE65YR
41         _AGE80
42         _AGE_G
43          _BMI5
44       _BMI5CAT
45        _RFBMI5
46        _EDUCAG
47       _SMOKER3
48       _RFSMOK3
49       VEGEDA1_
50       _MISVEGN
51       _VEGRESP
52       _VEGESUM
53        _VEGLT1
54         _VEG23
55       _FRUITEX
56       _VEGETEX

In [14]:
# This code selects the useful healthcare columns from the raw BRFSS dataset

selected_columns = [
    "DIABETE3",      # Diabetes status
    "GENHLTH",      # General health
    "PHYSHLTH",     # Physical health bad days
    "MENTHLTH",     # Mental health bad days
    "BLOODCHO",     # Cholesterol check
    "CHOLCHK",      # Cholesterol check
    "CVDINFR4",     # Heart attack
    "CVDCRHD4",     # Coronary heart disease
    "CVDSTRK3",     # Stroke
    "SEX",          # Sex
    "EDUCA",        # Education
    "INCOME2",      # Income
    "DIFFWALK",     # Difficulty walking
    "SMOKE100",     # Smoked at least 100 cigarettes
    "ALCDAY5",      # Alcohol consumption
    "FRUITJU1",     # Fruit juice consumption
    "FRUIT1",       # Fruit consumption
    "VEGETAB1",     # Vegetables consumption
    "EXERANY2",     # Physical activity
    "_AGEG5YR",     # Age group
    "_BMI5"         # BMI calculated variable
]

df_selected = df_raw[selected_columns]

df_selected.head()

,DIABETE3,GENHLTH,PHYSHLTH,MENTHLTH,BLOODCHO,CHOLCHK,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,...,INCOME2,DIFFWALK,SMOKE100,ALCDAY5,FRUITJU1,FRUIT1,VEGETAB1,EXERANY2,_AGEG5YR,_BMI5
0,3.0,5.0,15.0,18.0,1.0,1.0,2.0,2.0,2.0,2.0,...,3.0,1.0,1.0,888.0,305.0,310.0,101.0,2.0,9.0,4018.0
1,3.0,3.0,88.0,88.0,1.0,4.0,2.0,2.0,2.0,2.0,...,1.0,2.0,1.0,888.0,302.0,305.0,304.0,1.0,7.0,2509.0
2,3.0,4.0,15.0,88.0,1.0,1.0,7.0,2.0,1.0,2.0,...,99.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,2204.0
3,3.0,5.0,30.0,30.0,1.0,1.0,2.0,2.0,2.0,2.0,...,8.0,1.0,2.0,888.0,555.0,101.0,201.0,2.0,9.0,2819.0
4,3.0,5.0,20.0,88.0,1.0,1.0,2.0,2.0,2.0,2.0,...,77.0,2.0,2.0,888.0,777.0,102.0,320.0,2.0,9.0,2437.0

In [15]:
# This code shows the unique values in each selected column to understand what needs cleaning

for col in df_selected.columns:
    print("\nColumn:", col)
    print(sorted(df_selected[col].dropna().unique())[:30])

Column: DIABETE3
[1.0, 2.0, 3.0, 4.0, 7.0, 9.0]

Column: GENHLTH
[1.0, 2.0, 3.0, 4.0, 5.0, 7.0, 9.0]

Column: PHYSHLTH
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0]

Column: MENTHLTH
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0]

Column: BLOODCHO
[1.0, 2.0, 7.0, 9.0]

Column: CHOLCHK
[1.0, 2.0, 3.0, 4.0, 7.0, 9.0]

Column: CVDINFR4
[1.0, 2.0, 7.0, 9.0]

Column: CVDCRHD4
[1.0, 2.0, 7.0, 9.0]

Column: CVDSTRK3
[1.0, 2.0, 7.0, 9.0]

Column: SEX
[1.0, 2.0]

Column: EDUCA
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 9.0]

Column: INCOME2
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 77.0, 99.0]

Column: DIFFWALK
[1.0, 2.0, 7.0, 9.0]

Column: SMOKE100
[1.0, 2.0, 7.0, 9.0]

Column: ALCDAY5
[101.0, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 201.0, 202.0, 203.0, 204.0, 205.0, 206.0, 207.0, 208.0, 209.0, 210.0, 211.0, 212.0, 213.0, 214.0, 215.0, 216.0, 217.0, 218.0, 219.0, 220.0, 221.0, 222.0, 223.0]

Column: FRUITJU1
[101.0, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 108.0, 109.0, 110.0, 111.0, 112.0, 114.0, 115.0, 120.0, 125.0, 128.0, 130.0, 160.0, 175.0, 199.0, 201.0, 202.0, 203.0, 204.0, 205.0, 206.0, 207.0, 208.0, 209.0]

Column: FRUIT1
[101.0, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 108.0, 109.0, 110.0, 111.0, 112.0, 113.0, 114.0, 115.0, 118.0, 120.0, 121.0, 122.0, 124.0, 125.0, 126.0, 130.0, 140.0, 142.0, 150.0, 160.0, 172.0, 175.0, 199.0]

Column: VEGETAB1
[101.0, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 108.0, 109.0, 110.0, 112.0, 114.0, 115.0, 118.0, 120.0, 125.0, 126.0, 127.0, 130.0, 131.0, 175.0, 199.0, 201.0, 202.0, 203.0, 204.0, 205.0, 206.0, 207.0, 208.0]

Column: EXERANY2
[1.0, 2.0, 7.0, 9.0]

Column: _AGEG5YR
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0]

Column: _BMI5
[1202.0, 1205.0, 1211.0, 1215.0, 1216.0, 1217.0, 1220.0, 1221.0, 1222.0, 1233.0, 1237.0, 1240.0, 1245.0, 1248.0, 1253.0, 1255.0, 1256.0, 1262.0, 1263.0, 1269.0, 1270.0, 1271.0, 1275.0, 1278.0, 1284.0, 1285.0, 1288.0, 1291.0, 1292.0, 1293.0]

In [16]:
# This code cleans the diabetes target column and creates a binary target for machine learning

df_clean = df_selected.copy()

# Keep only clear diabetes answers:
# 1 = Yes diabetes
# 3 = No diabetes
df_clean = df_clean[df_clean["DIABETE3"].isin([1, 3])]

# Convert to binary:
# 1 = diabetes
# 0 = no diabetes
df_clean["Diabetes_binary"] = df_clean["DIABETE3"].map({
    1: 1,
    3: 0
})

# Check the result
print(df_clean["DIABETE3"].value_counts())
print(df_clean["Diabetes_binary"].value_counts())
print("New shape:", df_clean.shape)

DIABETE3
3.0    372104
1.0     57256
Name: count, dtype: int64
Diabetes_binary
0    372104
1     57256
Name: count, dtype: int64
New shape: (429360, 22)

In [17]:
# This code cleans simple yes/no health columns by replacing unclear answers with missing values

import numpy as np

binary_columns = [
    "BLOODCHO",
    "CHOLCHK",
    "CVDINFR4",
    "CVDCRHD4",
    "CVDSTRK3",
    "DIFFWALK",
    "SMOKE100",
    "EXERANY2"
]

for col in binary_columns:
    df_clean[col] = df_clean[col].replace({
        7: np.nan,   # Don't know / Not sure
        9: np.nan    # Refused
    })

# Check missing values after cleaning
df_clean[binary_columns].isnull().sum()

BLOODCHO     9180
CHOLCHK     63536
CVDINFR4     2004
CVDCRHD4     3508
CVDSTRK3     1102
DIFFWALK    14177
SMOKE100    17055
EXERANY2    37073
dtype: int64

In [2]:
import pandas as pd
import numpy as np

file_path = r"D:\document\AFTER_GRADUATION\DATAANALYSE\MINE\PROJECT4HEALTHCARE\LLCP2015.XPT"

df_raw = pd.read_sas(file_path, format="xport")

In [3]:
selected_columns = [
    "DIABETE3",
    "GENHLTH",
    "PHYSHLTH",
    "MENTHLTH",
    "BLOODCHO",
    "CHOLCHK",
    "CVDINFR4",
    "CVDCRHD4",
    "CVDSTRK3",
    "SEX",
    "EDUCA",
    "INCOME2",
    "DIFFWALK",
    "SMOKE100",
    "ALCDAY5",
    "FRUITJU1",
    "FRUIT1",
    "VEGETAB1",
    "EXERANY2",
    "_AGEG5YR",
    "_BMI5"
]

df_selected = df_raw[selected_columns]

In [4]:
df_clean = df_selected.copy()

df_clean = df_clean[df_clean["DIABETE3"].isin([1, 3])]

df_clean["Diabetes_binary"] = df_clean["DIABETE3"].map({
    1: 1,
    3: 0
})

In [12]:
# This code converts _BMI5 into a readable BMI value

print("Missing BMI before cleaning:", df_clean["_BMI5"].isnull().sum())

df_clean["BMI"] = df_clean["_BMI5"] / 100

df_clean[["_BMI5", "BMI"]].head()

Missing BMI before cleaning: 16753

    _BMI5    BMI
0  4018.0  40.18
1  2509.0  25.09
3  2819.0  28.19
4  2437.0  24.37
5  2652.0  26.52

In [13]:
# This code checks unclear and missing values before making cleaning decisions

import pandas as pd
import numpy as np

unclear_codes = {
    "DIABETE3": [2, 4, 7, 9],
    "GENHLTH": [7, 9],
    "PHYSHLTH": [77, 99],
    "MENTHLTH": [77, 99],
    "BLOODCHO": [7, 9],
    "CHOLCHK": [7, 9],
    "CVDINFR4": [7, 9],
    "CVDCRHD4": [7, 9],
    "CVDSTRK3": [7, 9],
    "DIFFWALK": [7, 9],
    "SMOKE100": [7, 9],
    "EXERANY2": [7, 9],
    "SEX": [7, 9],
    "EDUCA": [9],
    "INCOME2": [77, 99],
    "_AGEG5YR": [14]
}

summary = []

for col, codes in unclear_codes.items():
    unclear_count = df_selected[col].isin(codes).sum()
    missing_count = df_selected[col].isnull().sum()
    total_unclear_missing = unclear_count + missing_count
    percentage = (total_unclear_missing / len(df_selected)) * 100
    
    summary.append({
        "Column": col,
        "Unclear_values": unclear_count,
        "Missing_values": missing_count,
        "Total_unclear_or_missing": total_unclear_missing,
        "Percentage": round(percentage, 2)
    })

# Add BMI separately because BMI uses real missing values
bmi_missing = df_selected["_BMI5"].isnull().sum()

summary.append({
    "Column": "_BMI5",
    "Unclear_values": 0,
    "Missing_values": bmi_missing,
    "Total_unclear_or_missing": bmi_missing,
    "Percentage": round((bmi_missing / len(df_selected)) * 100, 2)
})

missing_summary_df = pd.DataFrame(summary)

missing_summary_df.sort_values(by="Percentage", ascending=False)

,Column,Unclear_values,Missing_values,Total_unclear_or_missing,Percentage
14,INCOME2,76204,3301,79505,18.01
5,CHOLCHK,5856,59154,65010,14.73
11,EXERANY2,2548,35444,37992,8.61
16,_BMI5,0,36398,36398,8.24
10,SMOKE100,3294,14255,17549,3.98
9,DIFFWALK,2260,12334,14594,3.31
0,DIABETE3,12089,7,12096,2.74
2,PHYSHLTH,9742,1,9743,2.21
4,BLOODCHO,9481,0,9481,2.15
3,MENTHLTH,7408,0,7408,1.68
15,_AGEG5YR,5336,0,5336,1.21
7,CVDCRHD4,3816,1,3817,0.86
6,CVDINFR4,2229,0,2229,0.50
13,EDUCA,1811,0,1811,0.41
8,CVDSTRK3,1290,0,1290,0.29
1,GENHLTH,1245,2,1247,0.28
12,SEX,0,0,0,0.00

In [14]:
# This code rebuilds df_clean 

df_clean = df_selected.copy()

# 1. Clean target column: keep only clear diabetes answers
# 1 = Diabetes, 3 = No diabetes
df_clean = df_clean[df_clean["DIABETE3"].isin([1, 3])]

df_clean["Diabetes_binary"] = df_clean["DIABETE3"].map({
    1: 1,
    3: 0
})

# 2. Keep unknown categories for high missing columns
# INCOME2: 77 and 99 become 9 = Unknown / Not reported
df_clean["INCOME2"] = df_clean["INCOME2"].replace({
    77: 9,
    99: 9
})

# CHOLCHK: 7 and 9 become 3 = Unknown / Not reported
df_clean["CHOLCHK"] = df_clean["CHOLCHK"].replace({
    7: 3,
    9: 3
})

# EXERANY2: 7 and 9 become 3 = Unknown / Not reported
df_clean["EXERANY2"] = df_clean["EXERANY2"].replace({
    7: 3,
    9: 3
})

# 3. Clean health columns
df_clean["GENHLTH"] = df_clean["GENHLTH"].replace({
    7: np.nan,
    9: np.nan
})

df_clean["PHYSHLTH"] = df_clean["PHYSHLTH"].replace({
    77: np.nan,
    88: 0,
    99: np.nan
})

df_clean["MENTHLTH"] = df_clean["MENTHLTH"].replace({
    77: np.nan,
    88: 0,
    99: np.nan
})

# 4. Clean low-missing binary columns
low_missing_binary_columns = [
    "BLOODCHO",
    "CVDINFR4",
    "CVDCRHD4",
    "CVDSTRK3",
    "DIFFWALK",
    "SMOKE100"
]

for col in low_missing_binary_columns:
    df_clean[col] = df_clean[col].replace({
        7: np.nan,
        9: np.nan
    })

# 5. Clean demographic columns
df_clean["EDUCA"] = df_clean["EDUCA"].replace({
    9: np.nan
})

df_clean["_AGEG5YR"] = df_clean["_AGEG5YR"].replace({
    14: np.nan
})

# 6. Remove rows with missing values only in low-missing columns
columns_to_drop_missing = [
    "GENHLTH",
    "PHYSHLTH",
    "MENTHLTH",
    "BLOODCHO",
    "CVDINFR4",
    "CVDCRHD4",
    "CVDSTRK3",
    "DIFFWALK",
    "SMOKE100",
    "SEX",
    "EDUCA",
    "_AGEG5YR"
]

print("Shape before final dropping:", df_clean.shape)

df_clean = df_clean.dropna(subset=columns_to_drop_missing)

print("Shape after final dropping:", df_clean.shape)
print("Remaining missing values:")
print(df_clean.isnull().sum())

Shape before final dropping: (429360, 22)
Shape after final dropping: (379170, 22)
Remaining missing values:
DIABETE3               0
GENHLTH                0
PHYSHLTH               0
MENTHLTH               0
BLOODCHO               0
CHOLCHK            43727
CVDINFR4               0
CVDCRHD4               0
CVDSTRK3               0
SEX                    0
EDUCA                  0
INCOME2                0
DIFFWALK               0
SMOKE100               0
ALCDAY5             1403
FRUITJU1           11890
FRUIT1             12862
VEGETAB1           16190
EXERANY2           18157
_AGEG5YR               0
_BMI5              22000
Diabetes_binary        0
dtype: int64

In [15]:
# This code replaces remaining missing values in CHOLCHK and EXERANY2 with Unknown category

df_clean["CHOLCHK"] = df_clean["CHOLCHK"].fillna(3)
df_clean["EXERANY2"] = df_clean["EXERANY2"].fillna(3)

# Check the result
print("Missing values in CHOLCHK:", df_clean["CHOLCHK"].isnull().sum())
print("Missing values in EXERANY2:", df_clean["EXERANY2"].isnull().sum())

print("\nCHOLCHK values:")
print(df_clean["CHOLCHK"].value_counts().sort_index())

print("\nEXERANY2 values:")
print(df_clean["EXERANY2"].value_counts().sort_index())

Missing values in CHOLCHK: 0
Missing values in EXERANY2: 0

CHOLCHK values:
CHOLCHK
1.0    256118
2.0     39212
3.0     71652
4.0     12188
Name: count, dtype: int64

EXERANY2 values:
EXERANY2
1.0    266987
2.0     92788
3.0     19395
Name: count, dtype: int64

In [16]:
# This code checks the remaining columns that still have missing values

remaining_columns = [
    "ALCDAY5",
    "FRUITJU1",
    "FRUIT1",
    "VEGETAB1",
    "_BMI5"
]

for col in remaining_columns:
    print("\nColumn:", col)
    print("Missing values:", df_clean[col].isnull().sum())
    print("Unique values sample:")
    print(sorted(df_clean[col].dropna().unique())[:40])

Column: ALCDAY5
Missing values: 1403
Unique values sample:
[101.0, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 201.0, 202.0, 203.0, 204.0, 205.0, 206.0, 207.0, 208.0, 209.0, 210.0, 211.0, 212.0, 213.0, 214.0, 215.0, 216.0, 217.0, 218.0, 219.0, 220.0, 221.0, 222.0, 223.0, 224.0, 225.0, 226.0, 227.0, 228.0, 229.0, 230.0, 777.0, 888.0, 999.0]

Column: FRUITJU1
Missing values: 11890
Unique values sample:
[101.0, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 108.0, 109.0, 110.0, 111.0, 112.0, 114.0, 115.0, 120.0, 125.0, 128.0, 130.0, 160.0, 199.0, 201.0, 202.0, 203.0, 204.0, 205.0, 206.0, 207.0, 208.0, 209.0, 210.0, 211.0, 212.0, 213.0, 214.0, 215.0, 216.0, 218.0, 220.0, 221.0, 222.0]

Column: FRUIT1
Missing values: 12862
Unique values sample:
[101.0, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 108.0, 109.0, 110.0, 111.0, 112.0, 113.0, 114.0, 115.0, 118.0, 120.0, 121.0, 122.0, 124.0, 125.0, 126.0, 130.0, 140.0, 142.0, 150.0, 160.0, 172.0, 175.0, 199.0, 201.0, 202.0, 203.0, 204.0, 205.0, 206.0, 207.0, 208.0, 209.0, 210.0]

Column: VEGETAB1
Missing values: 16190
Unique values sample:
[101.0, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 108.0, 109.0, 110.0, 112.0, 114.0, 115.0, 118.0, 120.0, 125.0, 126.0, 127.0, 130.0, 131.0, 175.0, 199.0, 201.0, 202.0, 203.0, 204.0, 205.0, 206.0, 207.0, 208.0, 209.0, 210.0, 211.0, 212.0, 213.0, 214.0, 215.0, 216.0, 217.0, 218.0]

Column: _BMI5
Missing values: 22000
Unique values sample:
[1202.0, 1205.0, 1211.0, 1215.0, 1216.0, 1217.0, 1220.0, 1222.0, 1233.0, 1237.0, 1240.0, 1253.0, 1255.0, 1256.0, 1262.0, 1263.0, 1269.0, 1270.0, 1278.0, 1284.0, 1285.0, 1288.0, 1291.0, 1292.0, 1293.0, 1295.0, 1300.0, 1304.0, 1306.0, 1307.0, 1308.0, 1316.0, 1323.0, 1325.0, 1329.0, 1331.0, 1333.0, 1334.0, 1335.0, 1339.0]

In [17]:
# This code converts _BMI5 into a readable BMI value and fills missing BMI using the median

df_clean["BMI"] = df_clean["_BMI5"] / 100

bmi_median = df_clean["BMI"].median()

df_clean["BMI"] = df_clean["BMI"].fillna(bmi_median)

print("BMI median used:", bmi_median)
print("Missing BMI after cleaning:", df_clean["BMI"].isnull().sum())

df_clean[["_BMI5", "BMI"]].head()

BMI median used: 26.95
Missing BMI after cleaning: 0

    _BMI5    BMI
0  4018.0  40.18
1  2509.0  25.09
3  2819.0  28.19
4  2437.0  24.37
5  2652.0  26.52

In [18]:
# This code shows the full value counts of alcohol consumption codes

df_clean["ALCDAY5"].value_counts(dropna=False).sort_index()

ALCDAY5
101.0     15045
102.0     12410
103.0      8242
104.0      3797
105.0      3922
106.0      1304
107.0      7837
201.0     30505
202.0     23119
203.0     12797
204.0     10825
205.0     10998
206.0      3915
207.0      2648
208.0      2940
209.0       239
210.0      8315
211.0        48
212.0      1540
213.0        78
214.0       592
215.0      6614
216.0       192
217.0        68
218.0       200
219.0        10
220.0      6818
221.0       171
222.0       158
223.0        63
224.0       176
225.0      2916
226.0       130
227.0       216
228.0       801
229.0       283
230.0     13199
777.0      2399
888.0    180885
999.0      1352
NaN        1403
Name: count, dtype: int64

In [19]:
# This code converts ALCDAY5 into estimated alcohol drinking days per month

def convert_alcohol_days(value):
    if pd.isna(value):
        return np.nan
    
    value = int(value)
    
    # 888 means no alcohol consumption
    if value == 888:
        return 0
    
    # 777 and 999 mean unknown/refused
    if value in [777, 999]:
        return np.nan
    
    # Codes 101-107 mean days per week
    # Convert weekly frequency to monthly frequency by multiplying by 4
    if 101 <= value <= 107:
        days_per_week = value - 100
        return days_per_week * 4
    
    # Codes 201-230 mean days per month
    if 201 <= value <= 230:
        days_per_month = value - 200
        return days_per_month
    
    return np.nan


df_clean["Alcohol_days_per_month"] = df_clean["ALCDAY5"].apply(convert_alcohol_days)

print("Missing values before imputation:", df_clean["Alcohol_days_per_month"].isnull().sum())

alcohol_median = df_clean["Alcohol_days_per_month"].median()

df_clean["Alcohol_days_per_month"] = df_clean["Alcohol_days_per_month"].fillna(alcohol_median)

print("Alcohol median used:", alcohol_median)
print("Missing values after imputation:", df_clean["Alcohol_days_per_month"].isnull().sum())

df_clean[["ALCDAY5", "Alcohol_days_per_month"]].head(10)

Missing values before imputation: 5154
Alcohol median used: 1.0
Missing values after imputation: 0

    ALCDAY5  Alcohol_days_per_month
0     888.0                     0.0
1     888.0                     0.0
3     888.0                     0.0
4     888.0                     0.0
5     888.0                     0.0
6     203.0                     3.0
9     888.0                     0.0
10    888.0                     0.0
11    888.0                     0.0
12    888.0                     0.0

In [20]:
# This code converts BRFSS fruit and vegetable frequency codes into times per day

def convert_food_frequency(value):
    if pd.isna(value):
        return np.nan
    
    value = int(value)
    
    # 777 = Don't know, 999 = Refused
    if value in [777, 999]:
        return np.nan
    
    # 300 means less than once per month
    if value == 300:
        return 0
    
    # Codes 101-199 mean times per day
    if 101 <= value <= 199:
        return value - 100
    
    # Codes 201-299 mean times per week
    # Convert weekly frequency to daily frequency
    if 201 <= value <= 299:
        return (value - 200) / 7
    
    # Codes 301-399 mean times per month
    # Convert monthly frequency to daily frequency
    if 301 <= value <= 399:
        return (value - 300) / 30
    
    return np.nan


df_clean["Fruit_juice_per_day"] = df_clean["FRUITJU1"].apply(convert_food_frequency)
df_clean["Fruit_per_day"] = df_clean["FRUIT1"].apply(convert_food_frequency)
df_clean["Vegetables_per_day"] = df_clean["VEGETAB1"].apply(convert_food_frequency)

food_columns = ["Fruit_juice_per_day", "Fruit_per_day", "Vegetables_per_day"]

print("Missing values before imputation:")
print(df_clean[food_columns].isnull().sum())

for col in food_columns:
    median_value = df_clean[col].median()
    df_clean[col] = df_clean[col].fillna(median_value)
    print(f"{col} median used:", median_value)

print("\nMissing values after imputation:")
print(df_clean[food_columns].isnull().sum())

df_clean[["FRUITJU1", "Fruit_juice_per_day", "FRUIT1", "Fruit_per_day", "VEGETAB1", "Vegetables_per_day"]].head(10)

Missing values before imputation:
Fruit_juice_per_day    166761
Fruit_per_day           31490
Vegetables_per_day      27674
dtype: int64
Fruit_juice_per_day median used: 0.42857142857142855
Fruit_per_day median used: 1.0
Vegetables_per_day median used: 0.7142857142857143

Missing values after imputation:
Fruit_juice_per_day    0
Fruit_per_day          0
Vegetables_per_day     0
dtype: int64

,FRUITJU1,Fruit_juice_per_day,FRUIT1,Fruit_per_day,VEGETAB1,Vegetables_per_day
0,305.0,0.166667,310.0,0.333333,101.0,1.000000
1,302.0,0.066667,305.0,0.166667,304.0,0.133333
3,555.0,0.428571,101.0,1.000000,201.0,0.142857
4,777.0,0.428571,102.0,2.000000,320.0,0.666667
5,101.0,1.000000,101.0,1.000000,101.0,1.000000
6,330.0,1.000000,202.0,0.285714,205.0,0.714286
9,201.0,0.142857,101.0,1.000000,101.0,1.000000
10,202.0,0.285714,201.0,0.142857,203.0,0.428571
11,203.0,0.428571,203.0,0.428571,306.0,0.200000
12,NaN,0.428571,NaN,1.000000,NaN,0.714286

In [22]:
# This code correctly converts BRFSS fruit and vegetable frequency codes into times per day

def convert_food_frequency(value):
    if pd.isna(value):
        return np.nan
    
    value = int(value)
    
    # 555 = Never
    if value == 555:
        return 0
    
    # 777 = Don't know, 999 = Refused
    if value in [777, 999]:
        return np.nan
    
    # 300 = Less than once per month
    if value == 300:
        return 0
    
    # 101-199 = times per day
    if 101 <= value <= 199:
        return value - 100
    
    # 201-299 = times per week
    if 201 <= value <= 299:
        return (value - 200) / 7
    
    # 301-399 = times per month
    if 301 <= value <= 399:
        return (value - 300) / 30
    
    return np.nan


df_clean["Fruit_juice_per_day"] = df_clean["FRUITJU1"].apply(convert_food_frequency)
df_clean["Fruit_per_day"] = df_clean["FRUIT1"].apply(convert_food_frequency)
df_clean["Vegetables_per_day"] = df_clean["VEGETAB1"].apply(convert_food_frequency)

food_columns = ["Fruit_juice_per_day", "Fruit_per_day", "Vegetables_per_day"]

print("Missing values before imputation:")
print(df_clean[food_columns].isnull().sum())

for col in food_columns:
    median_value = df_clean[col].median()
    df_clean[col] = df_clean[col].fillna(median_value)
    print(f"{col} median used:", median_value)

print("\nMissing values after imputation:")
print(df_clean[food_columns].isnull().sum())

df_clean[["FRUITJU1", "Fruit_juice_per_day", 
          "FRUIT1", "Fruit_per_day", 
          "VEGETAB1", "Vegetables_per_day"]].head(10)

Missing values before imputation:
Fruit_juice_per_day    19143
Fruit_per_day          17564
Vegetables_per_day     21429
dtype: int64
Fruit_juice_per_day median used: 0.1
Fruit_per_day median used: 1.0
Vegetables_per_day median used: 0.7142857142857143

Missing values after imputation:
Fruit_juice_per_day    0
Fruit_per_day          0
Vegetables_per_day     0
dtype: int64

,FRUITJU1,Fruit_juice_per_day,FRUIT1,Fruit_per_day,VEGETAB1,Vegetables_per_day
0,305.0,0.166667,310.0,0.333333,101.0,1.000000
1,302.0,0.066667,305.0,0.166667,304.0,0.133333
3,555.0,0.000000,101.0,1.000000,201.0,0.142857
4,777.0,0.100000,102.0,2.000000,320.0,0.666667
5,101.0,1.000000,101.0,1.000000,101.0,1.000000
6,330.0,1.000000,202.0,0.285714,205.0,0.714286
9,201.0,0.142857,101.0,1.000000,101.0,1.000000
10,202.0,0.285714,201.0,0.142857,203.0,0.428571
11,203.0,0.428571,203.0,0.428571,306.0,0.200000
12,NaN,0.100000,NaN,1.000000,NaN,0.714286

In [23]:
# This code checks the remaining missing values after cleaning and transformation

df_clean.isnull().sum().sort_values(ascending=False)

_BMI5                     22000
VEGETAB1                  16190
FRUIT1                    12862
FRUITJU1                  11890
ALCDAY5                    1403
DIABETE3                      0
Fruit_per_day                 0
Fruit_juice_per_day           0
Alcohol_days_per_month        0
BMI                           0
Diabetes_binary               0
_AGEG5YR                      0
EXERANY2                      0
SMOKE100                      0
GENHLTH                       0
DIFFWALK                      0
INCOME2                       0
EDUCA                         0
SEX                           0
CVDSTRK3                      0
CVDCRHD4                      0
CVDINFR4                      0
CHOLCHK                       0
BLOODCHO                      0
MENTHLTH                      0
PHYSHLTH                      0
Vegetables_per_day            0
dtype: int64

In [24]:
# This code creates the final clean dataset by removing old raw coded columns

columns_to_remove = [
    "DIABETE3",     # old diabetes column, replaced by Diabetes_binary
    "_BMI5",        # old BMI column, replaced by BMI
    "ALCDAY5",      # old alcohol column, replaced by Alcohol_days_per_month
    "FRUITJU1",     # old fruit juice column, replaced by Fruit_juice_per_day
    "FRUIT1",       # old fruit column, replaced by Fruit_per_day
    "VEGETAB1"      # old vegetable column, replaced by Vegetables_per_day
]

df_final = df_clean.drop(columns=columns_to_remove)

print("Final dataset shape:", df_final.shape)
print("\nMissing values in final dataset:")
print(df_final.isnull().sum().sort_values(ascending=False))

df_final.head()

Final dataset shape: (379170, 21)

Missing values in final dataset:
GENHLTH                   0
DIFFWALK                  0
Fruit_per_day             0
Fruit_juice_per_day       0
Alcohol_days_per_month    0
BMI                       0
Diabetes_binary           0
_AGEG5YR                  0
EXERANY2                  0
SMOKE100                  0
INCOME2                   0
PHYSHLTH                  0
EDUCA                     0
SEX                       0
CVDSTRK3                  0
CVDCRHD4                  0
CVDINFR4                  0
CHOLCHK                   0
BLOODCHO                  0
MENTHLTH                  0
Vegetables_per_day        0
dtype: int64

,GENHLTH,PHYSHLTH,MENTHLTH,BLOODCHO,CHOLCHK,CVDINFR4,CVDCRHD4,CVDSTRK3,SEX,EDUCA,...,DIFFWALK,SMOKE100,EXERANY2,_AGEG5YR,Diabetes_binary,BMI,Alcohol_days_per_month,Fruit_juice_per_day,Fruit_per_day,Vegetables_per_day
0,5.0,15.0,18.0,1.0,1.0,2.0,2.0,2.0,2.0,4.0,...,1.0,1.0,2.0,9.0,0,40.18,0.0,0.166667,0.333333,1.000000
1,3.0,0.0,0.0,1.0,4.0,2.0,2.0,2.0,2.0,6.0,...,2.0,1.0,1.0,7.0,0,25.09,0.0,0.066667,0.166667,0.133333
3,5.0,30.0,30.0,1.0,1.0,2.0,2.0,2.0,2.0,4.0,...,1.0,2.0,2.0,9.0,0,28.19,0.0,0.000000,1.000000,0.142857
4,5.0,20.0,0.0,1.0,1.0,2.0,2.0,2.0,2.0,5.0,...,2.0,2.0,2.0,9.0,0,24.37,0.0,0.100000,2.000000,0.666667
5,2.0,0.0,0.0,1.0,1.0,2.0,2.0,2.0,2.0,3.0,...,2.0,2.0,1.0,11.0,0,26.52,0.0,1.000000,1.000000,1.000000

In [25]:
# This code saves the final cleaned dataset as a CSV file

df_final.to_csv("diabetes_cleaned_final.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [26]:
# This code saves the cleaned dataset inside the cleaned data folder

df_final.to_csv(
    r"D:\document\AFTER_GRADUATION\DATAANALYSE\MINE\PROJECT4HEALTHCARE\data\cleaned\diabetes_cleaned_final.csv",
    index=False
)

print("Cleaned dataset saved in data/cleaned successfully!")

OSError: Cannot save file into a non-existent directory: 'D:\document\AFTER_GRADUATION\DATAANALYSE\MINE\PROJECT4HEALTHCARE\data\cleaned'

In [28]:
df_final.to_csv(
    r"D:\document\AFTER_GRADUATION\DATAANALYSE\MINE\PROJECT4HEALTHCARE\data\cleaned\diabetes_cleaned_final.csv",
    index=False
)

print("Cleaned dataset saved in data/cleaned successfully!")

Cleaned dataset saved in data/cleaned successfully!

In [29]:
# This code creates a small sample of the cleaned dataset for GitHub

df_sample = df_final.sample(n=5000, random_state=42)

df_sample.to_csv(
    r"D:\document\AFTER_GRADUATION\DATAANALYSE\MINE\PROJECT4HEALTHCARE\data\cleaned\diabetes_cleaned_sample.csv",
    index=False
)

print("Sample dataset saved successfully!")
print(df_sample.shape)

Sample dataset saved successfully!
(5000, 21)

In [1]:
import os

os.getcwd()

'C:\\Users\\ASUS'